version: '3'

services:
  strapi:
    image: strapi/strapi
    container_name: cdc-strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1338:1337'
    networks:
      - cdc

  postgres:
    image: postgres
    container_name: cdc-postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - cdc
    
networks:
  cdc:
    external: true  
