query getPage($locale: String!, $slug: String!) {
  pageBySlug(locale: $locale, slug: $slug) {
    id
    title
    Content {
      __typename
      ... on ComponentContentHeadline {
        id
        Title
        Text
      }
      ... on ComponentContentRichtext {
        id
        Text
      }
      ... on ComponentContentAccordion {
        accordion_item {
          title
          text
          image {
            url
          }
        }
      }
      ... on ComponentContentGrid {
        id
        Block {
          id
          Title
          RichText
        }
      }
    }
  }
}
