query getArtists($locale: String, $where: JSON, $limit: Int, $start: Int) {
  musicGroupsConnection(locale: $locale, where: $where) {
    aggregate {
      count
    }
  }
  musicGroups(
    locale: $locale
    where: $where
    sort: "name:asc"
    limit: $limit
    start: $start
  ) {
    id
    name
    slug
    music_genre
    repertoire
    formats
    description
    artists {
      id
      first_name
      last_name
      instrument
    }
    cover {
      id
      url
      formats
    }
  }
}
