query getPage($locale: String!, $slug: String!) {
  page: pageBySlug(locale: $locale, slug: $slug) {
    id
    title
    Content {
      __typename
      ... on ComponentContentHeadline {
        id
        Lead
        Image {
          id
          url
        }
        Title
        RichText
      }
      ... on ComponentContentSubtitle {
        id
        Text
      }
      ... on ComponentContentRichtext {
        id
        Text
      }
      ... on ComponentContentAccordion {
        accordion_item {
          title
          text
          image {
            url
          }
        }
      }
      ... on ComponentContentGrid {
        id
        Block {
          id
          Title
          RichText
        }
      }
      ... on ComponentContentLogos {
        id
        Title
        Images {
          id
          url
        }
      }
      ... on ComponentContentEventsGrid {
        id
        EventBlocks: EventBlock {
          id
          Title
          Canton {
            id
            abbreviation
          }
          RichText
        }
      }
      ... on ComponentContentDownloadList {
        id
        Title
        DownloadElements: DownloadElement {
          id
          Title
          Infos
          File {
            id
            url
          }
          ExternalLink
        }
      }
      ... on ComponentContentFigure {
        id
        Image {
          id
          url
        }
        RichText
        ImagePosition
      }

      ... on ComponentContentSlidesList {
        id
        Slides: SlideItem {
          id
          RichText
          Image {
            id
            url
          }
        }
      }

      ... on ComponentContentTestimonialsGrid {
        id
        Testimonials {
          id
          Texte
          Author
          Position
        }
      }
    }
  }
}
