name: Deploy backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-backend.yml
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: './backend/yarn.lock'

      - name: 🧶 Yarn this beauty!
        run: yarn

      - name: 🔗 Creates symlink
        run: |
          ln -s /home/jminguely/www/cdc/shared/backend/public/uploads ./public/

      - name: 🔨 Build admin panel
        run: yarn build

      - name: 🚀 Ship the whole thin
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzrl --delete'
          options: '--exclude=node_modules'
          ssh_options: ''
          src: './backend'
          dest: ${{vars.DEPLOY_DEST}}

      - name: � Install production dependencies on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: cd ~/www/cdc/backend && yarn --production --frozen-lockfile

      - name: �🧨 Kickstart node server (backend)
        run: curl --basic --user '${{ secrets.ALWAYSDATA_API }} account=jminguely:' --data '' --request POST https://api.alwaysdata.com/v1/site/765706/restart/

      - name: 🧨 Kickstart node server (frontend)
        run: curl --basic --user '${{ secrets.ALWAYSDATA_API }} account=jminguely:' --data '' --request POST https://api.alwaysdata.com/v1/site/765707/restart/
